### ISSUE TITLE
no way to notify virtualenv about local dir w/out virtualenvwrapper 

### ISSUE THREAD

**Issue by oryband** [jmcantrell/vim-virtualenv#24]
I'm using virtualenv without virtualenvwrapper. That is, in my project's dir I manually `virtualenv venv` which set the working virtualenv directory to be `./venv/`. I've no info on how to to activate virtualenv this way in vim. Setting `let g:virtualenv_directory = 'venv'` or to `./venv` or anything similar didn't help.

In addition, if I manually `source ./venv/bin/activate` and then activate vim, the plugin doesn't recognise this.

What am I doing wrong? In any case the documentation is lacking regarding this issue.

**Comment by fzdmd** [comment]
I have the same problem

**Comment by jarandaf** [comment]
@oryband @fzdmd same issue here

**Comment by oryband** [comment]
@jmcantrell is this project still maintained? i haven't succeeded in making this plugin work

**Comment by jmcantrell** [comment]
Is this still an issue? If `VIRTUAL_ENV` is set in your environment, the plugin should see it. Are you using gvim or MacVim?

**Comment by jmcantrell** [comment]
First, apologies for neglecting this issue. I've not used this project in quite a while and have not spent much time on maintenance. When I originally wrote it, I was using virtualenvwrapper most of the time, and this plugin reflects that, but I use venv directly now. My use cases are much simpler, and I'm hoping to rewrite some things to make this plugin much simpler, as well. Part of that will be addressing situations like this.

You all may have since moved on, and, if so, I don't blame you, but I just wanted to let you know that issues like this are part of the reason why I stopped eating my own dogfood with this project, and I hope to address it soon.

I'm going to close this, but feel free to reopen.
