### ISSUE TITLE
On Windows, double slashes are used in the virtualenv folder.

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [jmcantrell/vim-virtualenv#43]
On Windows 7, when you try to activate a virtual environment it uses double slashes for the path, rendering the plugin unable to load the right environment. This is the traceback:

```python
Error detected while processing function virtualenv#activate:
line   34:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\maciej_szlosarczyk\vimfiles\bundle\vim-virtualenv\autoload\pyvenv.py", line 9, in activate
    with open(activate) as f:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\maciej_szlosarczyk\\Virtualenvs/barbell\\Scripts\\activate_this.py'  
```

**Comment by 3e4** [comment]
I found this post because I recently started using your nice extension on Linux with Anaconda python (specify the anaconda3/envs folder as virtualenv location, no other modificatoin necessary), but it does not work on Windows. (I want a use it cross platform)

I could not reproduce your comment above, and also the code above is out of date? In pyenv.py, line 9, there is no such code.

I added a simple print statement in line 39 of pyenv.py (`print(activate)`)
and I get `c:\Users\user\Anaconda\envs/py35/Scripts/activate_this.py`, so no double slashes.

However, anaconda python on windows does not have an `activate_this.py` file anywhere. If I create a normal virtualenv, then it is present. The activate.bat is only in the root folder of anaconda (on linux there is a link to the root's activate in each environment). What would be the right way to modify vim-virtualenv to make it work with anaconda on windows?

**Comment by jmcantrell** [comment]
@3e4 I'm not sure why anaconda doesn't create the activate_this script. However, it shouldn't be necessary anymore since the scripts content is included with the plugin now.

**Comment by 3e4** [comment]
Just to let you know that virtualenv works now on Windows.

Thank you.

**Comment by jmcantrell** [comment]
@3e4 That's great news. Thanks!
