### ISSUE TITLE
does not work for 'local' venvs

### ISSUE THREAD

**Issue by skamsie** [jmcantrell/vim-virtualenv#60]
OK I have red the help and it seems that the plugin is looking for a `~/.virtualenvs` dir.

However I have only created virtualenvs for each project independently, for ex: `virtualenv -p /usr/local/bin/python2.7 venv`. This command creates a virtual environment 'venv' in the directory where it is executed.

It seems that vim-virtualenv does not detect these local venvs

**Comment by eyusupov** [comment]
Doing `let g:virtualenv_directory = '.'`makes it detect local venvs. I couldn't get it to work yet though, but it could be for other reasons.

**Comment by jmcantrell** [comment]
To clarify, `g:virtualenv_directory` is only used as a last resort when no `VIRTUAL_ENV` environment variable exists or when activating an env within vim by name `:VirtualEnvActivate myenv`. If you've already created and activated an env (no matter where it's located), `VIRTUAL_ENV` will be set to that directory, and the plugin will recognize it. If you're a virtualenvwrapper user and use the `PROJECT_HOME` environment variable, it will be used instead of `g:virtualenv_directory`, too.

Are you using gvim or MacVim? Either of those will likely not recognize your terminal emulator's environment. Console vim is the bestest, y'all.

**Comment by hanrok** [comment]
you can change your configuration from
`let g:virtualenv_directory = '.'`
to
`let g:virtualenv_directory = $PWD`
then you get it work.
But the issue here that in my scenario `:python` give me my global python (2.7) and `:!python` execute activated virtualenv python interpreter. very odd..

**Comment by jmcantrell** [comment]
Apologies for the late reply.

@hanrok is that still an issue with `:python` vs `:!python` version mismatch? That seems possible if vim is compiled against the system version of python2, but a different version exists in `PATH`.

I'm hoping to address the original issue soon with a bit of a rewrite.
