### ISSUE TITLE
No commands in Vim 8.1.2104 (Git Bash) on Windows 10

### ISSUE THREAD

**Issue by FilBot3** [jmcantrell/vim-virtualenv#67]
I seem to be having issues with Vim included with GitBash, and also Vim for Windows (which doesn't have `+python` enabled) allowing me to run `:VirtualEnvList` or any of the other commands. With `wildmenu` turned on, I can tab through commands, but the VirtualEnv* commands are not available. I continually get:

```
E492: Not an editor command: VirtualEnvList
```

I also have the Plugin installed into: `~/.vim/pack/vendor/start/vim-virtualenv/`, and it shows in my `:scriptnames` list of loaded scripts.

Is this plugin intended only to be used on Linux/MacOS machines?

**Comment by ivanovmg** [comment]
I confirm. However, with neovim v.0.4.2 it works fine.

I guess the problem is that vim simply does not see python.

For me both commands return 0 regardless of the fact that python is in PATH and PYTHONHOME and python37.dll is in DYNAMIC_PYTHON3_DLL environment variables.

:echo has("python")
:echo has("python3")

**Comment by ClonedOne** [comment]
@ivanovmg  I was finding the same problem with neovim 0.4.4, while using pyenv virtualenv. Installing the `neovim` pip package in the current virtualenv solved the issue for me. (see https://blog.cuffaro.com/blog/2018/04/16/pyenv-neovim)

**Comment by jmcantrell** [comment]
@FilBot3 You'll need `+python` for this plugin to work. I'm not sure what that process looks like for windows.
