### ISSUE TITLE
virtualenv_auto_activate doesn't try very hard

### ISSUE THREAD

**Issue by pdc1** [jmcantrell/vim-virtualenv#68]
Not sure this is really an issue, but I wanted to share an approach I used to make auto activate try a little harder.

I don't have a $VIRTUAL_ENV or $PROJECT_HOME, I just have a single virtual env with the specific python version my vim was compiled with.

I was hoping that setting g:virtualenv_auto_activate would detect and load the single virtual environment I have. It does not.

My suggestion is to add a third case to virtualenv#activate, so if there is no $VIRTUAL_ENV or $PROJECT_HOME, it will call virtualenv#names, and if there is a single environment, attempt to load it.

Like so (warning, script novice!)

     if len(name) == 0  "Figure out the name based on current file
        if isdirectory($VIRTUAL_ENV)
            [...]
        elseif isdirectory($PROJECT_HOME)
            [...]
        else
            let venv = virtualenv#names('')
            if len(venv) == 1
                let name = venv[0]
                let env_dir = g:virtualenv_directory.'/'.name
            endif
        endif
    else
        [...]
    endif

Thanks...

**Comment by jmcantrell** [comment]
First, apologies for the late reply. I've not used this project in quite a while and have neglected its maintenance. When I originally wrote it, I was using virtualenvwrapper most of the time, and this plugin reflects that, but I use venv directly now. My use cases are much simpler, and I'm hoping to rewrite some things to make this plugin much simpler, as well. Part of that will be addressing situations like this. I think your approach would work, but I'd like to fix it by just simplifying the whole activation.

You may have since moved on, and, if so, I don't blame you, but I just wanted to let you know that the issue you brought up is one of the reasons I stopped eating my own dogfood with this project, and I hope to address it soon.

**Comment by pdc1** [comment]
Thanks for the update :) I have mostly moved away from python integration with vim, but it's good to know your plans.

**Comment by retzzz** [comment]
I got same issue and use similar way to fix it. The first virtual env that was found will be activated.
```vim
 if len(name) == 0  "Figure out the name based on current file
    if isdirectory($VIRTUAL_ENV)
        [...]
    elseif isdirectory($PROJECT_HOME)
        [...]
    else
            for name in virtualenv#names('')
                let tmp_dir = g:virtualenv_directory . '/' . name
                if isdirectory(tmp_dir)
                    let env_dir = tmp_dir
                    break
                endif
            endfor
    endif
else
    [...]
endif
```
